version: "3"
services:

  user-service-db:
    image: postgres
    container_name: user-service-db
    environment:
      - POSTGRES_USER=fdifrison
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user-db
    volumes:
      - ./docker-volume/user-db:/var/lib/postgresql/data1
    ports:
      - "54321:5432"
    networks:
      - fdifrisonNet

  order-service-db:
    image: postgres
    container_name: order-service-db
    environment:
      - POSTGRES_USER=fdifrison
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=order-db
    volumes:
      - ./docker-volume/order-db:/var/lib/postgresql/data2
    ports:
      - "54322:5432"
    networks:
      - fdifrisonNet


  product-service-mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/product-db
    networks:
      - fdifrisonNet
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=product-service-mongo
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - fdifrisonNet

networks:
  fdifrisonNet:
    driver: "bridge"