spring:
  application:
    name: user-service


  r2dbc:
    password: admin
    username: fdifrison
    url: r2dbc:postgresql://localhost:54321/user-db
    name: user-db
  sql:
    init:
      data-locations: schema.sql
  jpa:
    show-sql: true


server:
  port: 8092
